### ISSUE TITLE
Port de la traduccion a la version psvita

### ISSUE THREAD

**Issue by cualquiercosa327** [UnderProject/UnderProjectNX#1]
Hola a todos,primero decir que gracias por vuestro trabajo.
Me gustaria saber si el archivo  game.win es similar al de la version psvita y poder usar el parche directamente o tendria que abrirlo e ir cambiando el dialogo uno a uno tal como estais haciendo 
para la version switch
gracias por todo

**Comment by D3fau4** [comment]
Si puedes mándame por correo (raulwii2@gmail.com) el archivo de PSP vita y le hecho un ojo

**Comment by cualquiercosa327** [comment]
Hola,haber si este finde semana puedo mandartelo.

En psvita los juegos vienen encriptados ,he visto una manera haciendo un backup con una aplicacion llamada maidump.

Cuando lo tenga te lo envio

Gracias



________________________________
De: Raúl Álvarez Quereda <notifications@github.com>
Enviado: miércoles, 26 de septiembre de 2018 19:47
Para: UnderProject/UnderProjectNX
Cc: cualquiercosa327; Author
Asunto: Re: [UnderProject/UnderProjectNX] Port de la traduccion a la version psvita (#1)


Si puedes mándame por correo (raulwii2@gmail.com<mailto:raulwii2@gmail.com>) el archivo de PSP vita y le hecho un ojo
