### ISSUE TITLE
REQUEST

### ISSUE THREAD

**Issue by Nastas95** [UnderProject/UnderProjectNX#3]
So, I'm Italian, and i would LOVE to see UNDERTALE in my native language on the switch. I can help translating the game into Italian and expand the UnderProjectNX project.

If you don't want me to help you, please consider translating the game into Italian, there already is a patch for the PC 1.1 version that you can use as a base. Thanks!

**Comment by D3fau4** [comment]
Okay but I need you to commit to help, speak to me out of discord: D3fau4#5696
