### ISSUE TITLE
hola tengo un problema con el traducir.bat

### ISSUE THREAD

**Issue by jxmxc1** [UnderProject/UnderProjectNX#4]
[WARN] prod.keys does not exist.
Invalid NCA header! Are keys correct?
Done!
El sistema no puede encontrar la ruta especificada.
Applying Patch
xdelta3: file open failed: read: game.win: El sistema no puede encontrar el archivo especificado.
Presione una tecla para continuar . . .

eso es lo que aparece en el log

**Comment by AlexSavel** [comment]
me aparece lo mismo ayuda por favor :(

**Comment by D3fau4** [comment]
Simplemente no tenéis las keys.dat, eso no lo podemos proporcionar por que tiene derechos de autor pero googlear un poco y las encontráis
