### ISSUE TITLE
Error con los caracteres especiales en las peleas

### ISSUE THREAD

**Issue by franciscobeltran** [UnderProject/UnderProjectNX#6]
Buenas! Al empezar el juego en la batalla con Flowey los siguientes caracteres aparecen en blanco:
 - á
 - é
 - í
 - ó
 - ú
 - ñ

Estoy usando la versión beta 0.4.1 con Atmosphere 0.8.2 en la versión 6.2.0 de la Nintendo Switch.

Adjunto algunas fotos del error:
![img_20190108_173032](https://user-images.githubusercontent.com/9264315/50844681-85e02b00-136b-11e9-9a77-ffa666b8b6c0.jpg)
![img_20190108_173047](https://user-images.githubusercontent.com/9264315/50844683-85e02b00-136b-11e9-9c62-3e51154ad0c6.jpg)
![img_20190108_173116](https://user-images.githubusercontent.com/9264315/50844685-85e02b00-136b-11e9-95b0-699eb5160841.jpg)

**Comment by D3fau4** [comment]
Gracias por avisar, debe ser que se me olvidó cambiar la fuente por las que lleva las tildes lo revisaré
